import { useContext } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { context } from "../context/Cartcontext";
import axios from "axios"
import { auth } from "../firebase";
import { onAuthStateChanged } from "firebase/auth"
function Cart(){
    useEffect( ()=>{
            onAuthStateChanged(auth,(user)=>{
                if(!user){
                    navigate("/login")
                }
            })
        })
    const navigate=useNavigate()
    const {pizzaItems, updatePizzaItems, user} = useContext(context)
    console.log(pizzaItems);
    const selectedItems = pizzaItems.filter(pizza => pizza.addedToCart === true);
    console.log(selectedItems);
    if(!selectedItems.length){
navigate('/menu');
return;
    }
    const totalValue = selectedItems.reduce( (total, item)=>{
        console.log(total + (item.quantity + item.price));
        
        return total + (item.quantity * item.price);
    },0)
     function countChanges(from, pizza) {
        if (from === "incre") {
            updatePizzaItems((items) => {
                return items.map((x) => {
                    if (x.name === pizza.name) {
                        return { ...x, quantity: x.quantity + 1 }
                    } else {
                        return x;
                    }
                })
            })
        } else if (pizza.quantity - 1 < 1) {
            updatePizzaItems((items) => {
                return items.map((x) => {
                    if (x.name === pizza.name) {
                        return { ...x, addedToCart: false, quantity:0 }
                    } else {
                        return x;
                    }
                })
            })
        } else {
            updatePizzaItems((items) => {
                return items.map((x) => {
                    if (x.name === pizza.name) {
                        return { ...x, quantity: x.quantity - 1 }
                    } else {
                        return x;
                    }
                })
            })
        }
    }

    async function handlePayment(){
const order = await axios.post(import.meta.env.VITE_BACKEND_URL+"/makeOrder",{amount: totalValue * 100})
// console.log(order);
initPayment(order.data.data);

  }
  function initPayment(order){
    console.log("init payment");
    console.log(order);
    
    
const options = {
  key: import.meta.env.VITE_RAZORPAY_KEY_ID, // Put your public Key ID here
        amount: order.amount, 
        currency: order.currency,
        name: "My MERN Store",
        description: "Test Transaction",
        order_id: order.id, // The unique ID generated by your backend
        handler: async(response)=>{
          console.log("handler fun");
          // 3. Pass user.uid directly into your verification payload
          const payload = {
            razorpay_order_id: response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature: response.razorpay_signature,
            userId: user.uid, // 👈 Grabbing it cleanly from context!,
            userName: auth.currentUser.email,
            cartItems: pizzaItems.filter(x=> x.addedToCart),
            amount: totalValue * 100
          };
          
          
await axios.post(import.meta.env.VITE_BACKEND_URL+"/verifyPayment",payload).then((success)=>{
    navigate("/menu")
    window.alert("payment verified")
    let resetPizzaValues = pizzaItems.map(x=>{
        return {
        ...x,
        addedToCart:false,
        quantity:0
        }
    })
    updatePizzaItems(resetPizzaValues);
}).catch(e=> window.alert("payment failed, kindly try again !"))
        },
        theme: {
          color: "#3399cc",
        }
}
const rzp = new window.Razorpay(options);
rzp.open();
  }

return (
    <>
    <div className="cart-container">
        <div className="cart-header">
            <span onClick={()=>navigate('/menu')}><i class="fa-solid fa-arrow-left"></i>Cart</span>
        </div>
        <div className="cart-body">
            <div className="product-container">
                  {selectedItems.map((x)=>{
                        return(
                            <div className="selectedProduct">
                    <div className="selected-prod-details">
                        <span>{x.name}</span>
                        <span>Medium | New Hand Tossed</span>
                    </div>
                    <div className="selected-prod-price-info">
                        <div className="button"><span className="pointerBtn" onClick={() => countChanges('decre',x)}>-</span> <span className="count">{x.quantity}</span><span className="pointerBtn" onClick={() => countChanges('incre',x)}>+</span></div>
                        <span className="price">{x.price}</span>
                </div>
            </div> 
                        )
                    })

                    }
        </div>
        <div className="bill-container">
             <div className="bill-header">
                <span className="border"></span>
                <div className="text">Bill Details</div>
                                <span className="border right"></span>
            </div>
        <div className="bill-data">
         <div className="value-config">
            <span className="key">Item's Total</span>
                        <span className="value">Rs. {totalValue}</span>
            </div> 
            <div className="value-config">
            <span className="key">Delivery Charges</span>
                        <span className="value">Free</span>
            </div> 
                        <div className="value-config total">
            <span className="key">Total</span>
                        <span className="value">{totalValue}</span>
            </div>   
        </div>
        </div>
    </div>

    <div className="added-cart-dom-fixed payNowDom show" onClick={handlePayment}>
    <div className="fixed-dom-wrapper">

    <div className="fixed-dom payNowDom">
    <span className="payNow">Pay Now</span>
    {/* <span>{totalQuantity} items</span>
    <span><i class="fa-solid fa-cart-shopping"></i>View Cart<i class="fa-solid fa-arrow-right"></i></span> */}
    </div>
    </div>
</div>
    </div>
    </>
)
}
export default Cart;